package:
  name: pylbl
  version: 0.1

source:
  git_rev: try-conda
  git_url: https://github.com/GRIPS-code/pyLBL.git

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - sqlite
    - pip
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/GRIPS-code/pyLBL.git
