# This workflow will install Python dependencies and run tests

name: unit-test

on: [push]

jobs:
  unit_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        os: ["ubuntu-latest", "macos-latest"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .
    - name: Create spectral database
      env:
        FTP_DB_DIR: ${{ secrets.FTP_DB_DIR }}
        HITRAN_API_KEY: ${{ secrets.HITRAN_API_KEY }}
      run: |
        cd tests
        pytest
